---
- hosts: test_group
  gather_facts: false
  tasks:
    - name: update user passwd
      user:
        name: "{{ item.name }}"
        password: "{{ item.chpass | password_hash('sha512') }}"
        update_password: always
      with_items:
        - { name: 'test', chpass: 'password'}